[package]
name = "forgeki-desktop"
version = "0.1.0"
description = "ForgeKi Desktop"
authors = ["ForgeKi contributors"]
repository = "https://github.com/legendki7/forge-cli"
license = "MIT"
edition = "2021"

[lib]
name = "forgeki_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
open = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-clipboard-manager = "2"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-updater = "2"
