import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { githubActionsPlugin, WORKFLOW_PATH } from './index.js';

let cwd: string;

beforeEach(async () => {
  cwd = await mkdtemp(path.join(tmpdir(), 'forge-actions-'));
});

afterEach(async () => {
  await rm(cwd, { recursive: true, force: true });
});

async function configureProject(
  scripts: Record<string, string> = { test: 'vitest' },
  lockfile = 'package-lock.json',
): Promise<void> {
  await writeFile(path.join(cwd, 'package.json'), JSON.stringify({ name: 'fixture', scripts }));
  if (lockfile) await writeFile(path.join(cwd, lockfile), '');
}

async function workflowDirectory(): Promise<string> {
  const directory = path.join(cwd, '.github', 'workflows');
  await mkdir(directory, { recursive: true });
  return directory;
}

describe('githubActionsPlugin', () => {
  it('rejects a missing package manager without creating directories', async () => {
    await configureProject({ test: 'vitest' }, '');
    const result = await githubActionsPlugin.apply({ cwd });

    expect(result).toMatchObject({ status: 'unsupported', createdFiles: [] });
    expect(result.message).toContain('no supported package-manager lockfile');
    await expect(readFile(path.join(cwd, WORKFLOW_PATH), 'utf8')).rejects.toMatchObject({
      code: 'ENOENT',
    });
  });

  it('rejects unknown and invalid projects', async () => {
    expect((await githubActionsPlugin.apply({ cwd })).message).toContain(
      'not a supported Node.js project',
    );
    await writeFile(path.join(cwd, 'package.json'), '{invalid');
    expect((await githubActionsPlugin.apply({ cwd })).message).toContain('package.json is invalid');
  });

  it('rejects projects without validation scripts', async () => {
    await configureProject({ start: 'node index.js' });
    const result = await githubActionsPlugin.apply({ cwd });

    expect(result.status).toBe('unsupported');
    expect(result.message).toContain('no lint, typecheck, test, or build script');
  });

  it('detects an existing empty workflow directory as partial', async () => {
    await workflowDirectory();
    await expect(githubActionsPlugin.detect({ cwd })).resolves.toMatchObject({
      detected: false,
      state: 'partial',
    });
  });

  it('preserves unrelated workflows while creating ci.yml', async () => {
    await configureProject();
    const directory = await workflowDirectory();
    const unrelatedPath = path.join(directory, 'release.yml');
    await writeFile(unrelatedPath, 'name: Release\n');

    const detection = await githubActionsPlugin.detect({ cwd });
    const result = await githubActionsPlugin.apply({ cwd });

    expect(detection).toMatchObject({
      state: 'partial',
      files: ['.github/workflows/release.yml'],
    });
    expect(result.status).toBe('applied');
    await expect(readFile(unrelatedPath, 'utf8')).resolves.toBe('name: Release\n');
  });

  it('never overwrites a custom ci.yml', async () => {
    await configureProject();
    const directory = await workflowDirectory();
    const workflowPath = path.join(directory, 'ci.yml');
    await writeFile(workflowPath, 'name: Custom CI\n');

    const detection = await githubActionsPlugin.detect({ cwd });
    const result = await githubActionsPlugin.apply({ cwd });

    expect(detection).toMatchObject({ detected: false, state: 'partial' });
    expect(result.status).toBe('skipped');
    await expect(readFile(workflowPath, 'utf8')).resolves.toBe('name: Custom CI\n');
  });

  it('is an idempotent no-op after generation', async () => {
    await configureProject({ lint: 'eslint .', test: 'vitest' });
    expect((await githubActionsPlugin.apply({ cwd })).status).toBe('applied');
    const original = await readFile(path.join(cwd, WORKFLOW_PATH), 'utf8');

    const detection = await githubActionsPlugin.detect({ cwd });
    const repeated = await githubActionsPlugin.apply({ cwd });

    expect(detection).toMatchObject({ detected: true, state: 'configured' });
    expect(repeated.status).toBe('skipped');
    await expect(readFile(path.join(cwd, WORKFLOW_PATH), 'utf8')).resolves.toBe(original);
  });

  it('handles concurrent application without corruption', async () => {
    await configureProject({ test: 'vitest', build: 'tsup' });
    const results = await Promise.all([
      githubActionsPlugin.apply({ cwd }),
      githubActionsPlugin.apply({ cwd }),
    ]);

    expect(results.map(({ status }) => status).sort()).toEqual(['applied', 'skipped']);
    const output = await readFile(path.join(cwd, WORKFLOW_PATH), 'utf8');
    expect(output).toContain('# Generated by ForgeKi');
    expect(output.endsWith('\n')).toBe(true);
  });
});
