import { access, mkdir, readFile, readdir } from 'node:fs/promises';
import path from 'node:path';
import {
  createFileSafely,
  detectProject,
  type ForgePlugin,
  type PluginApplyResult,
  type PluginContext,
  type PluginDetectionResult,
} from '@forgecli7/core';
import { generateWorkflow, recognizedScripts } from './workflow.js';

export const WORKFLOW_PATH = '.github/workflows/ci.yml';

async function detect(context: PluginContext): Promise<PluginDetectionResult> {
  const workflowDirectory = path.join(context.cwd, '.github', 'workflows');
  const workflowPath = path.join(context.cwd, WORKFLOW_PATH);

  if (await exists(workflowPath)) {
    const content = await readFile(workflowPath, 'utf8');
    const generated = content.includes('# Generated by ForgeKi');
    return {
      detected: generated,
      state: generated ? 'configured' : 'partial',
      files: [WORKFLOW_PATH],
      message: generated
        ? `GitHub Actions is already configured in ${WORKFLOW_PATH}.`
        : `${WORKFLOW_PATH} exists but was not generated by ForgeKi; it will be left unchanged.`,
    };
  }

  if (await exists(workflowDirectory)) {
    const entries = await safeReadDirectory(workflowDirectory);
    const workflows = entries.filter((file) => /\.ya?ml$/i.test(file));
    return {
      detected: false,
      state: 'partial',
      files: workflows.map((file) => `.github/workflows/${file}`),
      message:
        workflows.length > 0
          ? `GitHub Actions is partially configured; preserving ${workflows.length} unrelated workflow(s).`
          : 'GitHub Actions is partially configured; the workflow directory exists but ci.yml is missing.',
    };
  }

  return {
    detected: false,
    state: 'not-configured',
    files: [],
    message: 'GitHub Actions CI is not configured yet.',
  };
}

async function apply(context: PluginContext): Promise<PluginApplyResult> {
  const project = await detectProject(context.cwd);
  if (project.warnings.some((warning) => warning.includes('package.json is malformed'))) {
    return unsupported('GitHub Actions workflow was not created because package.json is invalid.');
  }
  if (project.framework === 'unknown') {
    return unsupported(
      'GitHub Actions workflow was not created because this directory is not a supported Node.js project.',
    );
  }
  if (project.packageManager === 'unknown') {
    return unsupported(
      'GitHub Actions workflow was not created because no supported package-manager lockfile was detected.',
    );
  }
  if (recognizedScripts(project).length === 0) {
    return unsupported(
      'GitHub Actions workflow was not created because no lint, typecheck, test, or build script was found.',
    );
  }

  const workflowDirectory = path.join(context.cwd, '.github', 'workflows');
  const workflowPath = path.join(context.cwd, WORKFLOW_PATH);
  await mkdir(workflowDirectory, { recursive: true });
  const created = await createFileSafely(workflowPath, generateWorkflow(project));

  return created
    ? {
        status: 'applied',
        message: `GitHub Actions workflow created: ${WORKFLOW_PATH}.`,
        createdFiles: [WORKFLOW_PATH],
        skippedFiles: [],
      }
    : {
        status: 'skipped',
        message: `${WORKFLOW_PATH} already exists. Existing workflow was left unchanged.`,
        createdFiles: [],
        skippedFiles: [WORKFLOW_PATH],
      };
}

function unsupported(message: string): PluginApplyResult {
  return { status: 'unsupported', message, createdFiles: [], skippedFiles: [] };
}

async function exists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function safeReadDirectory(directory: string): Promise<string[]> {
  try {
    return await readdir(directory);
  } catch {
    return [];
  }
}

export const githubActionsPlugin: ForgePlugin = {
  id: 'github-actions',
  name: 'GitHub Actions',
  description: 'Add project-aware GitHub Actions continuous integration.',
  detect,
  apply,
};
