import type { ProjectDetectionResult } from '@forgecli/core';
import { describe, expect, it } from 'vitest';
import { ACTION_VERSIONS, generateWorkflow, NODE_VERSIONS } from './workflow.js';

function project(overrides: Partial<ProjectDetectionResult> = {}): ProjectDetectionResult {
  return {
    directory: '/project',
    framework: 'node',
    packageManager: 'npm',
    language: 'javascript',
    scripts: { test: 'vitest' },
    dependencies: {},
    devDependencies: {},
    detectedFiles: ['package.json', 'package-lock.json'],
    warnings: [],
    ...overrides,
  };
}

describe('generateWorkflow', () => {
  it('generates Next.js pnpm CI with only existing scripts', () => {
    const output = generateWorkflow(
      project({
        framework: 'nextjs',
        packageManager: 'pnpm',
        scripts: { lint: 'next lint', test: 'vitest', build: 'next build' },
      }),
    );

    expect(output).toContain('run: corepack enable');
    expect(output).toContain('cache: pnpm');
    expect(output).toContain('run: pnpm install --frozen-lockfile');
    expect(output).toContain('run: pnpm run lint');
    expect(output).not.toContain('name: Typecheck');
  });

  it('generates React/Vite npm CI', () => {
    const output = generateWorkflow(
      project({ framework: 'react-vite', scripts: { test: 'vitest', build: 'vite build' } }),
    );

    expect(output).toContain('cache: npm');
    expect(output).toContain('run: npm ci');
    expect(output).toContain('run: npm run build');
  });

  it('generates Express yarn CI with Corepack', () => {
    const output = generateWorkflow(
      project({ framework: 'express', packageManager: 'yarn', scripts: { test: 'jest' } }),
    );

    expect(output).toContain('run: corepack enable');
    expect(output).toContain('run: yarn install --frozen-lockfile');
    expect(output).toContain('run: yarn test');
  });

  it('isolates Bun setup from the Node.js matrix', () => {
    const output = generateWorkflow(
      project({ packageManager: 'bun', detectedFiles: ['package.json', 'bun.lock'] }),
    );

    expect(output).toContain(`uses: ${ACTION_VERSIONS.setupBun}`);
    expect(output).toContain('run: bun install --frozen-lockfile');
    expect(output).toContain('run: bun run test');
    expect(output).not.toContain('matrix.node-version');
    expect(output).not.toContain(ACTION_VERSIONS.setupNode);
  });

  it('uses the centralized Node.js matrix and stable workflow shape', () => {
    const output = generateWorkflow(project());

    expect(output).toContain(`node-version: [${NODE_VERSIONS.join(', ')}]`);
    expect(output).toContain('# Generated by ForgeCLI\nname: CI\n');
    expect(output).toContain('      - main\n      - master\n  pull_request:');
    expect(output.endsWith('\n')).toBe(true);
  });

  it('supports one recognized validation script', () => {
    const output = generateWorkflow(project({ scripts: { typecheck: 'tsc --noEmit' } }));

    expect(output).toContain('name: Typecheck');
    expect(output).not.toContain('name: Lint');
    expect(output).not.toContain('name: Test');
    expect(output).not.toContain('name: Build');
  });

  it('renders all scripts in lint, typecheck, test, build order', () => {
    const output = generateWorkflow(
      project({ scripts: { build: 'build', test: 'test', lint: 'lint', typecheck: 'types' } }),
    );
    const positions = ['name: Lint', 'name: Typecheck', 'name: Test', 'name: Build'].map((value) =>
      output.indexOf(value),
    );

    expect(positions).toEqual([...positions].sort((left, right) => left - right));
  });

  it('is deterministic', () => {
    const input = project({ scripts: { lint: 'eslint .', test: 'vitest' } });
    expect(generateWorkflow(input)).toBe(generateWorkflow(input));
  });
});
