import type { PackageManager, ProjectDetectionResult } from '@forgecli7/core';

export const NODE_VERSIONS = [20, 22] as const;

export const ACTION_VERSIONS = {
  checkout: 'actions/checkout@v7',
  setupNode: 'actions/setup-node@v6',
  setupBun: 'oven-sh/setup-bun@v2',
} as const;

export const VALIDATION_SCRIPTS = ['lint', 'typecheck', 'test', 'build'] as const;
type ValidationScript = (typeof VALIDATION_SCRIPTS)[number];

export function recognizedScripts(project: ProjectDetectionResult): ValidationScript[] {
  return VALIDATION_SCRIPTS.filter((script) => script in project.scripts);
}

export function generateWorkflow(project: ProjectDetectionResult): string {
  const scripts = recognizedScripts(project);
  return project.packageManager === 'bun'
    ? renderBunWorkflow(project, scripts)
    : renderNodeWorkflow(project, scripts);
}

function renderNodeWorkflow(
  project: ProjectDetectionResult,
  scripts: readonly ValidationScript[],
): string {
  const packageManager = project.packageManager as Exclude<PackageManager, 'bun'>;
  const lines = workflowHeader();
  lines.push(
    'jobs:',
    '  test:',
    '    name: Node.js ${{ matrix.node-version }}',
    '    runs-on: ubuntu-latest',
    '    strategy:',
    '      fail-fast: false',
    '      matrix:',
    `        node-version: [${NODE_VERSIONS.join(', ')}]`,
    '    steps:',
    `      - uses: ${ACTION_VERSIONS.checkout}`,
  );

  if (packageManager === 'pnpm' || packageManager === 'yarn') {
    lines.push('      - name: Enable Corepack', '        run: corepack enable');
  }

  lines.push(
    '      - name: Set up Node.js',
    `        uses: ${ACTION_VERSIONS.setupNode}`,
    '        with:',
    '          node-version: ${{ matrix.node-version }}',
  );
  if (packageManager !== 'unknown' && hasLockfile(project)) {
    lines.push(`          cache: ${packageManager}`);
  }

  lines.push(
    '      - name: Install dependencies',
    `        run: ${installCommand(packageManager, hasLockfile(project))}`,
  );
  appendScriptSteps(lines, packageManager, scripts);
  return `${lines.join('\n')}\n`;
}

function renderBunWorkflow(
  project: ProjectDetectionResult,
  scripts: readonly ValidationScript[],
): string {
  const lines = workflowHeader();
  lines.push(
    'jobs:',
    '  test:',
    '    name: Bun',
    '    runs-on: ubuntu-latest',
    '    steps:',
    `      - uses: ${ACTION_VERSIONS.checkout}`,
    '      - name: Set up Bun',
    `        uses: ${ACTION_VERSIONS.setupBun}`,
    '      - name: Install dependencies',
    `        run: bun install${hasLockfile(project) ? ' --frozen-lockfile' : ''}`,
  );
  appendScriptSteps(lines, 'bun', scripts);
  return `${lines.join('\n')}\n`;
}

function workflowHeader(): string[] {
  return [
    '# Generated by ForgeKi',
    'name: CI',
    '',
    'on:',
    '  push:',
    '    branches:',
    '      - main',
    '      - master',
    '  pull_request:',
    '',
  ];
}

function appendScriptSteps(
  lines: string[],
  packageManager: PackageManager,
  scripts: readonly ValidationScript[],
): void {
  const labels: Record<ValidationScript, string> = {
    lint: 'Lint',
    typecheck: 'Typecheck',
    test: 'Test',
    build: 'Build',
  };
  for (const script of scripts) {
    lines.push(
      `      - name: ${labels[script]}`,
      `        run: ${scriptCommand(packageManager, script)}`,
    );
  }
}

function installCommand(packageManager: Exclude<PackageManager, 'bun'>, frozen: boolean): string {
  switch (packageManager) {
    case 'pnpm':
      return frozen ? 'pnpm install --frozen-lockfile' : 'pnpm install --no-frozen-lockfile';
    case 'npm':
      return frozen ? 'npm ci' : 'npm install';
    case 'yarn':
      return frozen ? 'yarn install --frozen-lockfile' : 'yarn install';
    case 'unknown':
      return 'npm install';
  }
}

function hasLockfile(project: ProjectDetectionResult): boolean {
  return project.detectedFiles.some((file) =>
    ['pnpm-lock.yaml', 'package-lock.json', 'yarn.lock', 'bun.lock', 'bun.lockb'].includes(file),
  );
}

function scriptCommand(packageManager: PackageManager, script: ValidationScript): string {
  switch (packageManager) {
    case 'pnpm':
      return `pnpm run ${script}`;
    case 'npm':
      return `npm run ${script}`;
    case 'yarn':
      return `yarn ${script}`;
    case 'bun':
      return `bun run ${script}`;
    case 'unknown':
      return `npm run ${script}`;
  }
}
